version: '3.8'
services:
  mongodb:
    image: mongo:7.0.2
    container_name: database
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
    networks:  
      - network

  nextjs:
    build: .
    container_name: ludys_pharma
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb 
    networks:
      - network

volumes:
  mongodb_data:

networks:
  network:
    driver: bridge